config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :blogs
  root 'blogs#index'
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.try(:admin?)
      can :access, :rails_admin #rails_adminへのアクセス
      can :manage, :all #すべてのモデルの編集
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  enum status: { 重要！: 1, できれば: 2, あとで: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :authenticate_user! #ブログ投稿や閲覧、編集、削除など）は、ログインしたユーザーのみに許可する
  before_action :set_q, only: [:index, :search]

  def index
    @q = Blog.ransack(params[:q])
    @blogs = @q.result.page(params[:page]).per(4)
    # @blogs = Blog.order(created_at: :desc)
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to @blog, notice: "ブログを投稿しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: "ブログを更新しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: "ブログを削除しました。"
  end

  def search
    @results = @q.result #ransackメソッドで取得したデータをActiveRecord_Relationのオブジェクトに変換するメソッド。
  end

  private
  def set_q
    @q = Blog.ransack(params[:q]) #検索フォームから送られるパラメーターを元に検索
    #ransackメソッドはwhereメソッドみたいなイメージ
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
  
  def blog_params
    params.require(:blog).permit(:title, :content)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:title, :content, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", :placeholder => "おいしいお寿司"%>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control", :rows=> "20"%>
  </div>

  <div class="actions">
    <%= form.submit "投稿する" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h2>投稿編集</h2>
<div class="col-sm-8 container">
  <%= render 'form', blog: @blog %>
</div>
<div class="col-sm-4 container">
  <a class="twitter-timeline" data-width="500" data-height="600" data-theme="light" href="https://twitter.com/12a1070?ref_src=twsrc%5Etfw">Tweets by 12a1070</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>

app/views/blogs/index.html.erb
<% if current_user.try(:admin?) %>
  <h2>ブログ記事一覧(管理ユーザー)</h2>
<% else %>
  <h2>ブログ記事一覧</h2>
<% end %>

<div class="index">
  <div class="col-sm-8 container">
  <%= search_form_for @q do |f| %>
    <%= f.label :title_or_content, 'キーワードで検索' %>
    <%= f.search_field :title_or_content_cont, class: "form-control", :placeholder => "あいまいなワードで検索"%> 
    <%# カラム名_contメソッド---検索したワードであいまい検索 %>
    <%# search_fieldにすると、右側にバツが表示 %>
    <br>
    <%= f.submit '検索', class: 'btn btn-default'%>
  <% end %>
  <%= sort_link(@q, :title, "タイトルで並び替え") %>
  <div class="scroll-list jscroll">
    <% @blogs.each do |blog| %>     
    <article>
      <h3><%= blog.title %></h3>
      <p><%= blog.content.truncate(25) %></p>
      <p class="morebt">
        <%= link_to 'もっと見る', blog %> 
        <%= link_to '編集する', edit_blog_path(blog) %> 
        <%= link_to '削除する', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    </article>
    <% end %>
    <%= paginate @blogs %>
  </div>
    
  </div>
  <div class="col-sm-4 container tweet">
  <a class="twitter-timeline" data-width="500" data-height="600" data-theme="light" href="https://twitter.com/12a1070?ref_src=twsrc%5Etfw">Tweets by 12a1070</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
</div>

<script>
  //kaminari + jscrollを使った無限スクロールの実装
  $(function() {
    $('.jscroll').jscroll({
      contentSelector: '.scroll-list',// 無限に追加する要素は、どこに入れる？
      nextSelector: 'span.next:last a'
    });
  });
  //トップページへ
  $(window).on('scroll', function() {
   scrollHeight = $(document).height();
   scrollPosition = $(window).height() + $(window).scrollTop();
  });
</script>

app/views/blogs/new.html.erb
<h2>新規投稿</h2>
<div class="col-sm-8 container">
  <%= render 'form', blog: @blog %>
</div>
<div class="col-sm-4 container">
  <a class="twitter-timeline" data-width="500" data-height="600" data-theme="light" href="https://twitter.com/12a1070?ref_src=twsrc%5Etfw">Tweets by 12a1070</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>

app/views/blogs/show.html.erb
<h2>投稿内容</h2>

<div class="col-sm-8 container">
  <h4><%= @blog.title %></h4>
  <div class="content">
    <p><%= @blog.content %></p>
  </div>
</div>
<div class="col-sm-4 container">
  <a class="twitter-timeline" data-width="500" data-height="600" data-theme="light" href="https://twitter.com/12a1070?ref_src=twsrc%5Etfw">Tweets by 12a1070</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body id="top">
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Pipilog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <% if current_user.try(:admin?) %>
            <li><%= link_to "管理画面", rails_admin_path %></li>
          <% end %>
          <li><%= link_to "ブログ一覧", blogs_path %></li>
          <li><%= link_to "新規投稿", new_blog_path %></li>
          <li><%= link_to "タスク", tasks_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">その他 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "新規投稿", new_blog_path %></li>
            <li><%= link_to "新規投稿", new_blog_path %></li>
            <li><%= link_to "新規投稿", new_blog_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "新規投稿", new_blog_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "新規投稿", new_blog_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>

  <% if user_signed_in? %>
    <p class="login">Logged in as <strong> <%= link_to current_user.email, edit_user_registration_path %></strong></p>
  <% end %>

    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
    <%= yield %>
    <div class="backtop"><!--bodyのタグにtop追加してるから上まで飛ぶ-->
    <a href="#top">
      <strong>TOP</strong>
     </a>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.collection_radio_buttons :status, Task.statuses, :first, :first %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<% n = 1  %>
<% @tasks.each do |task| %>
  <div class="box">
    <label for=<%= "btn#{n}" %> class="label_accordion"><%= task.title %></label>
    <input type="checkbox" id=<%= "btn#{n}" %> class="btn">

    <div class="content_accordion">
      <p>
        <% if task.status == "重要！" %>⚠️<% end %>
        <% if task.status == "できれば" %>⭕️<% end %>
        <% if task.status == "あとで" %>❎<% end %>
        <%= task.content %>
      </p>
      <p>
        <%= link_to 'Show', task %> | 
        <%= link_to 'Edit', edit_task_path(task) %> | 
        <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    </div>
  </div>
  <% n += 1 %>
<% end %>

<hr>
<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>